(()=>{'use strict';
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let records=[],active=null,offset=0,sequence=0,busy=false;
const format=d=>new Date(d).toLocaleString('es-AR',{timeZone:'America/Argentina/Buenos_Aires'}), label=s=>s.toLowerCase().replace(/^./,c=>c.toUpperCase());
const currency=value=>value==null?'No informado':Number(value).toLocaleString('es-AR',{style:'currency',currency:'ARS'});
async function api(path,data){const res=await fetch(window.MT2_API||'/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(window.MT2_API?{...data,op:path}:data),signal:AbortSignal.timeout(90000)});const json=await res.json();if(!res.ok)throw Error(json.error||'No se pudo completar la operación');if(path==='import'&&json.record?.skipped)throw Error(json.record.reason);return json;}
async function load(){const seq=++sequence;$('refresh').disabled=true;
try{const result=await api('list',{branch:$('branch').value,state:'',search:$('search').value,offset});if(seq!==sequence)return;records=result.filter(r=>r.estado!=='CONFIRMADO OK');render();$('message').textContent='';$('updated').textContent='Consultado '+new Date().toLocaleTimeString('es-AR',{timeZone:'America/Argentina/Buenos_Aires'});}
catch(e){if(seq===sequence)$('message').textContent='No se pudo actualizar. Conservamos la última consulta. '+e.message;}
finally{if(seq===sequence)$('refresh').disabled=false;}}
function render(){$('count').textContent=`· ${records.length} en esta página`;$('page').textContent='Página '+(offset/50+1);$('prev').disabled=offset===0;$('next').disabled=records.length<50;
$('records').innerHTML=records.length?records.map(r=>{const d=r.data;const names={'ENVIADO A SUCURSAL':'CONFIRMAR DESTINO','RECIBIDO EN SARMIENTO':'RECIBIR EN SARMIENTO','ENVIADO A DESTINO':'ENVIAR A DESTINO','RECIBIDO EN SUCURSAL':'RECIBIR EN SUCURSAL','CONFIRMADO OK':'CONFIRMADO OK','DIFERENCIAS':'DIFERENCIAS'};return `<article class="card"><div class="card-left"><div class="card-title-row"><h3>Remito ${esc(d.remito)}</h3><button class="btn view" data-id="${esc(r.id)}">VER</button></div><span class="badge ${r.estado==='REVISAR DESTINO'?'warn':r.estado==='DIFERENCIAS'?'danger':r.estado==='CONFIRMADO OK'?'ok':''}">${esc(label(r.estado))}</span></div><div class="card-center">${Object.entries({'Fecha':d.fecha,'Desde':d.desde,'Hacia':d.hacia||'Revisar destino','Prendas':d.total_prendas,'Circuito':!d.hacia?'POR DEFINIR':d.via_sarmiento?'CON SARMIENTO':'DIRECTO','Etapa actual':label(r.estado)}).map(([k,v])=>`<div class="info"><span class="label">${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('')}<div class="client-info"><strong>${esc(d.local)}</strong><br>${esc(d.cliente)} · Código ${esc(d.codigo_cliente)}</div></div><div class="card-right">${actions(r).map(a=>`<button class="btn ${a==='DIFERENCIAS'?'warn':'primary'}" data-id="${esc(r.id)}" data-next="${esc(a)}">${names[a]}</button>`).join('')}</div></article>`;}).join(''):'<div class="empty">No hay remitos pendientes para estos filtros.</div>';}
function actions(r){switch(r.estado){case 'REVISAR DESTINO':return ['ENVIADO A SUCURSAL'];case 'ENVIADO A SUCURSAL':return [r.data.via_sarmiento?'RECIBIDO EN SARMIENTO':'RECIBIDO EN SUCURSAL'];case 'RECIBIDO EN SARMIENTO':return ['ENVIADO A DESTINO'];case 'ENVIADO A DESTINO':return ['RECIBIDO EN SUCURSAL'];case 'RECIBIDO EN SUCURSAL':return ['CONFIRMADO OK','DIFERENCIAS'];case 'DIFERENCIAS':return ['CONFIRMADO OK'];default:return [];}}
function detail(r){const d=r.data;$('detail-title').textContent=d.remito;
$('detail').innerHTML='<div class="fields">'+Object.entries({'Local':d.local,'Cliente':d.cliente,'Código cliente':d.codigo_cliente,'Origen de carpeta':d.desde,'Destino':d.hacia||'Sin asignar','Fecha':d.fecha,'Vendedor':d.vendedor||'No informado','Estado':label(r.estado),'Prendas':d.total_prendas,'Total':currency(d.importe_total)}).map(([k,v])=>`<div><small>${esc(k)}</small>${esc(v)}</div>`).join('')+'</div>'+`<div class="table-wrap"><table><thead><tr><th>Artículo</th><th>Color</th><th>Talle</th><th>Cantidad</th><th>Precio</th><th>Importe</th></tr></thead><tbody>${d.items.map(i=>`<tr>${['articulo','color','talle','cantidad','precio','importe'].map(k=>`<td>${esc(i[k]??'—')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
$('detail-dialog').showModal();}
function openAction(r,next){if(!actions(r).includes(next))return;active=r;$('action-form').reset();$('action').value=next;$('action-error').textContent='';$('action-title').textContent=r.estado==='REVISAR DESTINO'?'Confirmar destino':label(next);$('action-remito').textContent='Remito '+r.data.remito;$('code').value='';$('destination').value='';$('destination-wrap').hidden=r.estado!=='REVISAR DESTINO';$('destination').required=r.estado==='REVISAR DESTINO';$('differences-fields').hidden=next!=='DIFERENCIAS';$('observation').required=next==='DIFERENCIAS';$('action-dialog').showModal();$('code').focus();}
function fileData(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({name:file.name,base64:reader.result.split(',')[1]});reader.onerror=()=>reject(Error('No se pudo leer el archivo'));reader.readAsDataURL(file);});}
$('records').addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(!b)return;const r=records.find(r=>r.id===b.dataset.id);if(!r)return;if(b.dataset.next)openAction(r,b.dataset.next);else detail(r);});
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{if(!busy)$(b.dataset.close).close();});
document.querySelectorAll('dialog').forEach(d=>d.addEventListener('cancel',e=>{if(busy)e.preventDefault();}));
$('import-open').onclick=()=>{$('import-error').textContent='';$('import-dialog').showModal();};
$('import-form').onsubmit=async e=>{e.preventDefault();busy=true;$('import-submit').disabled=true;$('import-error').textContent='Leyendo y guardando…';try{const f=$('pdf').files[0];if(!f||f.size>15*1024*1024)throw Error('Seleccioná un PDF de hasta 15 MB');const data=await fileData(f);const result=await api('import',{filename:f.name,base64:data.base64,origin:$('origin').value});$('import-dialog').close();offset=0;$('branch').value='';$('state').value='';$('search').value='';await load();await detail(result.record);}catch(e){$('import-error').textContent=e.message;}finally{busy=false;$('import-submit').disabled=false;}};
$('action-form').onsubmit=async e=>{e.preventDefault();busy=true;$('action-submit').disabled=true;$('action-error').textContent='';try{const files=Array.from($('evidence').files);if(files.length>3||files.some(f=>f.size>5*1024*1024))throw Error('Máximo 3 archivos de 5 MB');if($('action').value==='DIFERENCIAS'&&!$('observation').value.trim())throw Error('Detallá las diferencias');const result=await api('action',{id:active.id,version:active.version,estado:$('action').value,codigo:$('code').value.trim(),observacion:$('observation').value,destino:$('destination').value,files:await Promise.all(files.map(fileData))});$('action-dialog').close();active=null;await load();}catch(e){$('action-error').textContent=e.message;}finally{busy=false;$('action-submit').disabled=false;}};
async function status(){try{const s=window.MT2_API?await api('status',{}):await (await fetch('/api/status',{signal:AbortSignal.timeout(5000)})).json();if(!$('origin').options.length){for(const id of ['branch','origin','destination'])s.branches.forEach(b=>$(id).add(new Option(b,b)));$('destination').prepend(new Option('Seleccionar…',''));$('destination').value='';}
const v=s.sync;$('sync-label').textContent=v.running?`${v.phase||'Buscando novedades'} · ${v.pending} pendientes`:v.error?'Requiere atención':v.automatic?'Automática · cada 1 minuto':'Búsqueda manual';$('sync-status').innerHTML=`<p>${esc(s.database)}<br>Última revisión: ${v.last_success?esc(format(v.last_success)):'Todavía no realizada'} · Pendientes: ${v.pending}<br>Importaciones realizadas: ${v.totals?.imported||0} · Antiguos omitidos como confirmados: ${v.totals?.skipped||0}</p>${v.error?'<p>'+esc(v.error)+'</p>':''}${(v.errors||[]).map(e=>`<p>${esc(e.file)}: ${esc(e.error)} (${e.attempts} intentos)</p>`).join('')}`;$('sync-run').disabled=v.running;}catch(e){$('sync-label').textContent='Servicio local no disponible';}}
$('sync-run').onclick=async()=>{try{await api('sync',{});await status();}catch(e){$('message').textContent=e.message;}};
$('refresh').onclick=()=>{load();status();};['branch','state'].forEach(id=>$(id).onchange=()=>{offset=0;load();});let timer;$('search').oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>{offset=0;load();},300);};$('prev').onclick=()=>{offset=Math.max(0,offset-50);load();};$('next').onclick=()=>{offset+=50;load();};
status().then(load);setInterval(()=>{if(!document.hidden){if(!busy)load();status();}},15000);
})();
