const {test}=require('node:test');
const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const D=require('../shared/domain.js'), E=require('../server/engine.js'), Store=require('../tools/local-store.cjs');
const actor={sub:'operator1',email:'test@example.invalid',role:'operator',origins:['DEPOSITO']};
function payload(n=25){return {version:2,id:'20261007_'+randomUUID(),responsable:'DAVID',origen:'DEPOSITO',destino:'AV2',bultos:2,catalogVersion:'test-catalog',reviewedUnknown:true,scans:Array.from({length:n},(_,i)=>({id:randomUUID(),code:i%2?'000123':'ART!NEGRO!M'}))};}
function rig(){const s=new Store();return {s,e:E.create(s),p:payload()};}
test('repeated submission preserves exactly one number, TXT and row, including repeated scans',()=>{const {s,e,p}=rig();const a=e.handle({action:'submit',payload:p},actor).job;assert.equal(a.state,'READY');for(let i=0;i<10;i++)assert.equal(e.handle({action:'submit',payload:p},actor).job.remito,a.remito);assert.equal(s.data.counter,1);assert.equal(Object.keys(s.data.files).length,2);assert.equal(Object.keys(s.data.rows).length,1);assert.equal(s.data.files[a.fileId].body,D.content(p));});
for(const stage of ['before_manifest','after_manifest','after_save_RECEIVED','before_number','after_number','before_txt','after_txt','after_save_TXT_VERIFIED','before_publish','after_publish','after_save_READY']){
  test('process death at '+stage+' recovers without duplication',()=>{const {s,e,p}=rig();s.fault={stage,crash:true};assert.throws(()=>e.handle({action:'submit',payload:p},actor),/Corte/);s.offset+=9*60*1000;e.recover(10);let j=e.handle({action:'submit',payload:p},actor).job;s.offset+=9*60*1000;e.recover(10);j=e.handle({action:'status',id:p.id},actor).job;assert.equal(j.state,'READY');assert.equal(s.data.counter,1);assert.equal(Object.keys(s.data.rows).length,1);assert.equal(Object.keys(s.data.files).length,2);assert.equal(s.data.files[j.fileId].body,D.content(p));});
}
test('failure before TXT never publishes a row',()=>{const {s,e,p}=rig();s.fault={stage:'before_txt'};const j=e.handle({action:'submit',payload:p},actor).job;assert.notEqual(j.state,'READY');assert.equal(Object.keys(s.data.rows).length,0);s.offset+=60000;e.recover();assert.equal(s.get(p.id).state,'READY');});
test('verified TXT removed by consumer is not recreated on recovery',()=>{const {s,e,p}=rig();s.fault={stage:'after_save_TXT_VERIFIED',crash:true};assert.throws(()=>e.handle({action:'submit',payload:p},actor));const j=s.get(p.id);delete s.data.files[j.txtId];s.offset+=9*60*1000;e.recover();assert.equal(s.get(p.id).state,'ATTENTION');assert.equal(s.data.files[j.txtId],undefined);assert.equal(Object.keys(s.data.rows).length,0);});
test('tampered TXT blocks cuadernillo',()=>{const {s,e,p}=rig();s.fault={stage:'after_txt',crash:true};assert.throws(()=>e.handle({action:'submit',payload:p},actor));s.data.files[s.get(p.id).txtId].body='wrong';s.offset+=9*60*1000;e.recover();assert.equal(s.get(p.id).state,'ATTENTION');assert.equal(Object.keys(s.data.rows).length,0);});
test('payload collision and foreign owner cannot reuse ID',()=>{const {e,p}=rig();e.handle({action:'submit',payload:p},actor);assert.throws(()=>e.handle({action:'submit',payload:{...p,bultos:3}},actor),{code:'CONFLICT'});assert.throws(()=>e.handle({action:'status',id:p.id},{...actor,sub:'another'}),{code:'FORBIDDEN'});});
test('duplicate event IDs, no review, blank payload and over-limit rejected before side effects',()=>{const {e,s,p}=rig();for(const invalid of [{...p,scans:[]},{...p,reviewedUnknown:false},{...p,scans:[p.scans[0],p.scans[0]]},payload(D.LIMIT+1)])assert.throws(()=>e.handle({action:'submit',payload:invalid},actor));assert.equal(s.data.counter,0);assert.equal(Object.keys(s.data.jobs).length,0);});
test('daily workload: 200 remitos and 5000 scans with retry storm',()=>{const s=new Store(),e=E.create(s);for(let i=0;i<200;i++){const p=payload(25),a={...actor,sub:'operator'+(i%10)};e.handle({action:'submit',payload:p},a);e.handle({action:'submit',payload:p},a);}assert.equal(s.data.counter,200);assert.equal(Object.keys(s.data.rows).length,200);assert.equal(Object.values(s.data.jobs).reduce((n,j)=>n+j.count,0),5000);assert.ok(Object.values(s.data.jobs).every(j=>j.state==='READY'));});
test('retry and cancellation require supervisor, and issued remitos cannot be cancelled',()=>{const {e,p}=rig();e.handle({action:'submit',payload:p},actor);assert.throws(()=>e.handle({action:'retry',id:p.id},actor),{code:'FORBIDDEN'});assert.throws(()=>e.handle({action:'cancel',id:p.id,reason:'error de carga'},{...actor,role:'admin'}),{code:'STATE'});});
