(() => {
 'use strict';
 const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS'}).format(n);
 const branch=window.RioContext?.branch||'', cfg=window.CajaConfig, key='rio_caja_draft_v1:'+branch;
 const sections=[['expenses','Detalle / gastos',['Detalle','Monto']],['vouchers','Vales local',['Nombre y apellido','Tipo','Monto','Firma / conformidad']],['withdrawals','Retiros en efectivo',['Nombre y apellido','Monto','Firma / conformidad']],['deposits','Depósitos / transferencias',['Nombre y apellido','Origen','Movimiento','Monto']]];
 const fields=[['mp','Total MPago + MPQR'],['cards','Total tarjetas'],['go','Total Go Cuotas'],['counted','Efectivo contado al cierre']];
 const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Argentina/Buenos_Aires',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const blank=()=>({date:today(),responsible:'',responsibleCode:'',notes:'',sharedDrawer:branch==='AV2',f9Mode:'local',webClose:null,f9:'',mp:0,cards:0,go:0,cashSales:0,counted:0,expenses:[],vouchers:[],withdrawals:[],deposits:[],shipping:[{name:'Shipnow',cash:0,digital:0},{name:'Expreso',cash:0,digital:0}]});
 let data=blank(), record=null, dirty=false, offset=0, webState='loading', latestWeb=null;
 try{const saved=JSON.parse(localStorage.getItem(key));if(saved){data={...blank(),...saved.data};record=saved.record||null;dirty=!!saved.dirty;}}catch{}
 data=CajaRules.normalize(data);
 function expenseCell(index,row){return `<td><select required aria-label="Concepto de gasto fila ${index+1}" data-section="expenses" data-index="${index}" data-field="concept"><option value="">${esc(row.name&&!row.concept?row.name+' · ELEGIR CONCEPTO':'ELEGIR CONCEPTO')}</option>${CajaRules.concepts.map(c=>`<option value="${c}" ${row.concept===c?'selected':''}>${c}</option>`).join('')}</select>${CajaRules.personConcepts.has(row.concept)?`<input required aria-label="A quién corresponde el gasto fila ${index+1}" data-section="expenses" data-index="${index}" data-field="person" maxlength="120" placeholder="A QUIÉN CORRESPONDE" value="${esc(row.person||'')}">`:''}</td><td class="print-value">${esc(row.name)}</td>`;}
 function voucherCell(index,row){return `<td><select required aria-label="Legajo del vale fila ${index+1}" data-section="vouchers" data-index="${index}" data-field="staffCode"><option value="">${esc(row.name&&!row.staffCode?row.name+' · ELEGIR LEGAJO':'ELEGIR LEGAJO')}</option>${staff.map(r=>`<option value="${esc(r.id)}" ${row.staffCode===r.id?'selected':''}>${esc(r.id+' · '+CajaRules.upper(r.nombre))}</option>`).join('')}</select></td><td class="print-value">${esc(row.name)}${row.staffCode?' · LEGAJO '+esc(row.staffCode):''}</td>`;}
 let accounts=[];
 function accountCell(index,row){return `<td><select required aria-label="Cuenta de origen fila ${index+1}" data-section="deposits" data-index="${index}" data-field="account"><option value="">Elegir cuenta</option>${accounts.map(a=>`<option value="${esc(a)}" ${row.account===a?'selected':''}>${esc(a)}</option>`).join('')}<option value="other" ${row.account==='other'?'selected':''}>Otra</option></select>${row.account==='other'?`<input required aria-label="Nombre de otra cuenta fila ${index+1}" data-section="deposits" data-index="${index}" data-field="otherAccount" maxlength="240" placeholder="Nombre de la cuenta especial" value="${esc(row.otherAccount||'')}">`:''}</td><td class="print-value">${esc(row.account==='other'?row.otherAccount:row.account||'')}</td>`;}
 async function loadAccounts(){try{const response=await fetch('../confirmacion-depositos/index.html',{cache:'no-store'});if(!response.ok)throw new Error();const doc=new DOMParser().parseFromString(await response.text(),'text/html');accounts=[...doc.querySelectorAll('#cuentaSelect option')].map(o=>CajaRules.upper(o.value)).filter(Boolean);if(!accounts.length)throw new Error();renderSections();updateTotals();}catch{status('No se pudieron cargar las cuentas de Depósitos. Recargá para reintentar.',true);}}
 let staff=window.CajaStaff.cache();
 function staffOptions(){const query=$('staffSearch').value.trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const selected=data.responsibleCode||'';$('responsible').innerHTML='<option value="">Elegí un responsable</option>'+staff.filter(r=>r.id===selected||(r.id+' '+r.nombre).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(query)).map(r=>`<option value="${esc(r.id)}">${esc(r.id+' · '+CajaRules.upper(r.nombre))}</option>`).join('');$('responsible').value=selected;$('responsiblePrint').textContent=data.responsible+(selected?' · Legajo '+selected:'');}
 async function loadStaff(){try{$('staffStatus').textContent='Actualizando legajos de Asistencia…';staff=await CajaStaff.load();staffOptions();renderSections();updateTotals();$('staffStatus').textContent='Legajos de Asistencia actualizados.';}catch(e){$('staffStatus').textContent=staff.length?'Usando el padrón reciente de Asistencia guardado en este navegador.':e.message;}}
 $('staffSearch').addEventListener('input',staffOptions);$('reloadStaff').onclick=loadStaff;
 if(!record){data.date=today();}
 function status(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error);}
 function persist(){try{localStorage.setItem(key,JSON.stringify({data,record,dirty}));return true;}catch{status('No se pudo guardar el borrador en este navegador. Guardá en Supabase antes de salir.',true);return false;}}
 function cellInput(section,index,field,value,type='text'){return `<td><input aria-label="${esc(section)} fila ${index+1} ${esc(field)}" data-section="${section}" data-index="${index}" data-field="${field}" type="text" ${type==='number'?'data-money inputmode="decimal" autocomplete="off"':'maxlength="240"'} value="${esc(type==='number'?CajaMoney.display(value):value)}"></td><td class="print-value">${type==='number'?money(Number(value)||0):esc(value)}</td>`;}
 function cellSelect(section,index,value){const opts=section==='vouchers'?[['cash','Efectivo'],['goods','Mercadería']]:[['cash','Desde caja'],['external','Transferencia externa']];return `<td><select aria-label="${section} fila ${index+1} tipo" data-section="${section}" data-index="${index}" data-field="kind">${opts.map(([v,t])=>`<option value="${v}" ${value===v?'selected':''}>${t}</option>`).join('')}</select></td><td class="print-value">${esc(opts.find(o=>o[0]===value)?.[1])}</td>`;}
 function renderSections(){ $('movementSections').innerHTML=sections.map(([s,title,headers])=>`<section class="movement ${data[s].length?'has-rows':'is-empty'}" data-movement="${s}"><h3>${title}<span class="row-count no-print">${data[s].length} ${data[s].length===1?'registro':'registros'}</span></h3><p class="section-hint no-print">${({expenses:'Elegí un concepto y cargá el importe pagado.',vouchers:'Seleccioná el legajo y si el vale es en efectivo o mercadería.',withdrawals:'Registrá quién retira el efectivo y cuánto se lleva.',deposits:'Elegí la cuenta e indicá si el dinero salió de caja.'})[s]}</p>${!data[s].length?'<p class="empty-state no-print">Sin movimientos cargados. Usá el botón de abajo para agregar uno.</p>':''}<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}<th class="remove no-print"></th></tr></thead><tbody>${data[s].map((r,i)=>`<tr>${s==='expenses'?expenseCell(i,r):s==='vouchers'?voucherCell(i,r):cellInput(s,i,'name',r.name)}${s==='deposits'?accountCell(i,r):''}${['vouchers','deposits'].includes(s)?cellSelect(s,i,r.kind):''}${cellInput(s,i,'amount',r.amount,'number')}${['vouchers','withdrawals'].includes(s)?cellInput(s,i,'signature',r.signature):''}<td class="remove no-print"><button type="button" data-remove="${s}" data-index="${i}" aria-label="Eliminar fila ${i+1} de ${title}">×</button></td></tr>`).join('')}</tbody></table></div><div class="section-footer"><button type="button" data-add="${s}">+ Agregar ${s==='expenses'?'gasto':s==='vouchers'?'vale':s==='withdrawals'?'retiro':'depósito / transferencia'}</button><span class="section-total" id="total-${s}"></span></div></section>`).join(''); }
 function render(){ $('branchLabel').textContent=branch==='NAZCA'?'AVELLANEDA 2900':window.RioContext?.label(branch)||branch;for(const id of ['date','notes'])$(id).value=data[id];$('f9').value=CajaMoney.display(data.f9);$('f9').setCustomValidity('');staffOptions();renderSections();$('closingInputs').innerHTML=fields.filter(([id])=>branch!=='WEB'||id!=='counted').map(([id,label])=>`<label class="closing-field">${branch==='AV2'&&id==='cards'?'Tarjetas LOCAL':branch==='WEB'&&id==='cards'?'Tarjetas WEB':branch==='AV2'&&id==='counted'?'Efectivo contado TOTAL · LOCAL + WEB':label}<input id="${id}" type="text" data-money inputmode="decimal" autocomplete="off" value="${CajaMoney.display(data[id])}"></label>`).join('');$('shipping').innerHTML=`<table><thead><tr><th>Tipo de envío</th><th>Efectivo</th><th>Depo / MP</th><th>Total</th></tr></thead><tbody>${data.shipping.map((r,i)=>`<tr><td>${esc(r.name)}</td>${cellInput('shipping',i,'cash',r.cash,'number')}${cellInput('shipping',i,'digital',r.digital,'number')}<td id="ship-${i}"></td></tr>`).join('')}</tbody></table>`;renderShared();updateTotals(); }
 function renderShared(){
  const panel=$('sharedPanel');panel.hidden=!['AV2','WEB'].includes(branch);if(panel.hidden)return;
  if(branch==='WEB'){panel.innerHTML='<h3>CAJA WEB</h3><p>Cargá sólo los movimientos WEB. El efectivo físico se cuenta una sola vez en Avellaneda. Guardá este cierre antes del cierre LOCAL.</p>';return;}
  panel.innerHTML=`<h3>CAJA COMPARTIDA · AVELLANEDA + WEB</h3><label class="no-print"><input id="sharedDrawer" type="checkbox" ${data.sharedDrawer?'checked':''}> Incorporar cierre WEB del día</label>${data.sharedDrawer?`<label>F9 que estás informando<select id="f9Mode"><option value="local" ${data.f9Mode!=='combined'?'selected':''}>SÓLO AVELLANEDA / LOCAL</option><option value="combined" ${data.f9Mode==='combined'?'selected':''}>TOTAL LOCAL + WEB</option></select></label><p role="status">${webState==='ready'?'CIERRE WEB INCORPORADO · VERSIÓN '+data.webClose.version:webState==='stale'?'WEB CAMBIÓ: REVISÁ Y ACTUALIZÁ EL CIERRE ANTES DE GUARDAR O IMPRIMIR.':webState==='pending'?'PENDIENTE: WEB DEBE GUARDAR SU CIERRE DEL MISMO DÍA.':webState==='error'?'NO SE PUDO CONSULTAR WEB. REINTENTÁ.':'CONSULTANDO CIERRE WEB…'}</p><button type="button" id="refreshWeb" class="no-print">${webState==='stale'?'Incorporar versión WEB actualizada':'Actualizar cierre WEB'}</button><div id="sharedBreakdown"></div><div id="webDetails"></div><p>Cargá aquí sólo los movimientos LOCAL. El efectivo contado incluye toda la caja física, LOCAL + WEB.</p>`:''}`;
  $('sharedDrawer').onchange=e=>{data.sharedDrawer=e.target.checked;renderShared();change();if(data.sharedDrawer)checkWeb();};
  if($('f9Mode'))$('f9Mode').onchange=e=>{data.f9Mode=e.target.value;change();};
  if($('refreshWeb'))$('refreshWeb').onclick=()=>checkWeb(true);
 }
 async function checkWeb(incorporate=false){
  if(branch!=='AV2'||!data.sharedDrawer)return;
  const date=data.date;
  try{const rows=await request({action:'web_close',date});if(date!==data.date)return;latestWeb=rows[0]||null;
   if(!latestWeb)webState='pending';
   else if(data.webClose&&(data.webClose.id!==latestWeb.id||data.webClose.version!==latestWeb.version)&&!incorporate)webState='stale';
   else {const next={id:latestWeb.id,version:latestWeb.version,data:latestWeb.data};const changed=JSON.stringify(next)!==JSON.stringify(data.webClose);data.webClose=next;webState='ready';if(changed){dirty=true;persist();}}
  }catch{webState='error';}renderShared();updateTotals();
 }
 function webDetails(){
  if(!$('webDetails'))return;
  const w=data.webClose?.data;if(!w){$('webDetails').replaceChildren();return;}
  $('webDetails').innerHTML='<details class="web-details"><summary>VER MOVIMIENTOS WEB · '+esc(w.responsible)+'</summary>'+sections.map(([key,title])=>'<h4>'+esc(title.toUpperCase())+' · WEB</h4>'+(w[key]?.length?'<ul>'+w[key].map(r=>'<li>'+esc(r.name)+(r.staffCode?' · LEGAJO '+esc(r.staffCode):'')+' · '+esc(key==='deposits'?(r.account==='other'?r.otherAccount:r.account||'')+' · '+(r.kind==='cash'?'DESDE CAJA':'TRANSFERENCIA EXTERNA'):r.kind==='goods'?'MERCADERÍA':r.kind==='cash'?'EFECTIVO':'')+' · '+money(r.amount)+(r.signature?' · '+esc(r.signature):'')+'</li>').join('')+'</ul>':'<p>SIN MOVIMIENTOS</p>')).join('')+'<h4>ENVÍOS WEB</h4><ul>'+(w.shipping||[]).map(r=>'<li>'+esc(r.name)+' · EFECTIVO '+money(r.cash)+' · DEPO / MP '+money(r.digital)+'</li>').join('')+'</ul>'+(w.notes?'<p>OBSERVACIONES WEB: '+esc(w.notes)+'</p>':'')+'</details>';
 }
 function updateTotals(){webDetails();try{const t=CajaMath.shared(data,branch);for(const [s] of sections)$('total-'+s).textContent='Total: '+money(t[s]);data.shipping.forEach((r,i)=>$('ship-'+i).textContent=money((CajaMath.cents(r.cash)+CajaMath.cents(r.digital))/100));if($('sharedBreakdown')&&t.web){const rows=[['F9',t.local.saleTotal,t.web.saleTotal],['TARJETAS',Number(data.cards||0),Number(data.webClose.data.cards||0)],['MP',Number(data.mp||0),Number(data.webClose.data.mp||0)],['GO CUOTAS',Number(data.go||0),Number(data.webClose.data.go||0)],['GASTOS',t.local.expenses,t.web.expenses],['VALES',t.local.vouchers,t.web.vouchers],['RETIROS',t.local.withdrawals,t.web.withdrawals],['DEPÓSITOS / TRANSFERENCIAS',t.local.deposits,t.web.deposits],['ENVÍOS',t.local.shipping,t.web.shipping],['EFECTIVO ESPERADO',t.local.expected,t.web.expected],['VENTA FINAL',t.local.final,t.web.final]];$('sharedBreakdown').innerHTML='<div class=table-wrap><table><thead><tr><th>CONCEPTO</th><th>LOCAL</th><th>WEB</th><th>TOTAL</th></tr></thead><tbody>'+rows.map(([label,l,w])=>'<tr><td>'+label+'</td><td data-label=LOCAL>'+money(l)+'</td><td data-label=WEB>'+money(w)+'</td><td data-label=TOTAL>'+money(Math.round((l+w)*100)/100)+'</td></tr>').join('')+'</tbody></table></div><p>Efectivo contado atribuible a LOCAL: '+money(t.localCounted)+' (contado TOTAL − esperado WEB). La diferencia corresponde a la caja compartida.</p>';}$('summary').innerHTML=[[branch==='AV2'&&data.sharedDrawer?'Venta total LOCAL + WEB (F9)':'Venta total (F9)',t.saleTotal],['Venta en efectivo calculada',t.cashSales],[branch==='AV2'&&data.sharedDrawer?'Total de efectivo esperado · caja compartida':'Total de efectivo esperado al cierre',t.expected],...(branch==='WEB'?[]:[['1-10 (SOBRANTE) −',t.surplus],['1-10 (FALTANTE) +',t.shortage]]),['Envíos (Shipnow + Expreso) −',t.shipping],['VENTA FINAL',t.final]].map(([k,v],i)=>`<div ${k==='VENTA FINAL'?'class="final"':''}><dt>${k}</dt><dd>${money(v)}</dd></div>`).join('');}catch(e){status(e.message,true);}}
 function change(){data=CajaRules.normalize(data);dirty=true;updateTotals();if(persist())status('Borrador guardado en este navegador · pendiente de guardar en Supabase.');}
 $('sheet').addEventListener('input',e=>{const el=e.target;if(el.tagName==='TEXTAREA'||(el.tagName==='INPUT'&&!el.hasAttribute('data-money')&&el.type!=='date')){const pos=el.selectionStart;el.value=CajaRules.upper(el.value);if(pos!==null)el.setSelectionRange(pos,pos);}if(el.id==='staffSearch')return;let value=el.value;if(el.hasAttribute('data-money')){try{value=CajaMoney.update(el);el.setCustomValidity('');}catch(err){el.setCustomValidity(err.message);status(err.message,true);return;}}if(el.id==='responsible'){const r=staff.find(r=>r.id===el.value);data.responsibleCode=r?.id||'';data.responsible=CajaRules.upper(r?.nombre||'');$('responsiblePrint').textContent=r?CajaRules.upper(r.nombre)+' · LEGAJO '+r.id:'';}else if(el.dataset.section){const r=data[el.dataset.section][Number(el.dataset.index)];r[el.dataset.field]=value;if(el.dataset.section==='vouchers'&&el.dataset.field==='staffCode'){const employee=staff.find(x=>x.id===value);r.name=CajaRules.upper(employee?.nombre||'');}if(el.dataset.section==='expenses'){r.name=r.concept+(CajaRules.personConcepts.has(r.concept)&&r.person?' - '+r.person.trim():'');}if(el.dataset.field==='concept'||el.dataset.field==='staffCode'||(el.dataset.section==='deposits'&&el.dataset.field==='account')){renderSections();change();return;}const printCell=el.closest('td')?.nextElementSibling;if(printCell?.classList.contains('print-value'))printCell.textContent=el.hasAttribute('data-money')?money(Number(value)||0):el.dataset.section==='expenses'?r.name:el.tagName==='SELECT'?CajaRules.upper(el.selectedOptions[0].textContent):el.value;}else if(el.id==='sharedDrawer'||el.id==='f9Mode')return;else if(el.id in data)data[el.id]=value;change();});
 $('sheet').addEventListener('change',e=>{if(e.target.tagName==='SELECT')e.target.dispatchEvent(new Event('input',{bubbles:true}));});
 $('sheet').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.add){const s=b.dataset.add;if(data[s].length>=100){status('Máximo 100 filas por sección.',true);return;}data[s].push({name:'',amount:0,signature:'',kind:'cash',account:'',otherAccount:'',concept:'',person:'',staffCode:''});renderSections();change();}if(b.dataset.remove){data[b.dataset.remove].splice(Number(b.dataset.index),1);renderSections();change();}});
 function validate(){CajaRules.validateExpenses(data.expenses);for(const r of data.vouchers){if(!staff.some(x=>x.id===r.staffCode))throw new Error('ELEGÍ UN LEGAJO DE ASISTENCIA PARA CADA VALE.');}if(!data.responsibleCode||!staff.some(r=>r.id===data.responsibleCode))throw new Error('Elegí un responsable del padrón de Asistencia.');if(!$('sheet').reportValidity())throw new Error('Completá fecha, responsable y montos válidos.');for(const [s] of sections)for(const r of data[s])if(!String(r.name||'').trim())throw new Error('Completá el detalle o nombre de cada fila, o eliminá las filas vacías.');for(const r of data.deposits){if(!accounts.includes(r.account)&&r.account!=='other')throw new Error('Elegí una cuenta de origen en cada depósito o transferencia.');if(r.account==='other'&&!String(r.otherAccount||'').trim())throw new Error('Escribí el nombre de la cuenta especial.');}if(branch==='AV2'&&data.sharedDrawer&&(!data.webClose||webState!=='ready'))throw new Error('Actualizá e incorporá el cierre WEB del mismo día antes de guardar o imprimir.');CajaMath.shared(data,branch);}
 async function request(payload){
 if(!cfg.url||!cfg.key)throw new Error('La conexión con el proyecto nuevo todavía no está configurada.');
 const response=await fetch(cfg.url+'/functions/v1/movimientos-caja-api',{method:'POST',headers:{apikey:cfg.key,Authorization:'Bearer '+cfg.gatewayKey,'Content-Type':'application/json'},body:JSON.stringify({...payload,branch}),signal:AbortSignal.timeout(20000)});
 const result=await response.json();if(!response.ok)throw new Error(result.error||'No se pudo completar la operación.');return result;
 }
 $('saveButton').onclick=async()=>{const b=$('saveButton');try{validate();b.disabled=true;if(!record){data.date=today();$('date').value=data.date;}if(branch==='AV2'&&data.sharedDrawer){await checkWeb();validate();}const snapshot=CajaRules.normalize(data);const original=JSON.stringify(snapshot);const same=record&&record.date===snapshot.date;const saved=await request({action:'save',data:snapshot,...(same?{id:record.id,version:record.version}:{})});if(!saved?.length)throw new Error('La planilla cambió en otro equipo. Abrila desde Historial antes de editarla.');const editedWhileSaving=JSON.stringify(data)!==original;if(!editedWhileSaving){data={...data,...saved[0].data};}record={id:saved[0].id,date:saved[0].business_date,version:saved[0].version};dirty=editedWhileSaving;renderShared();updateTotals();persist();status(dirty?'Planilla guardada. Hay cambios posteriores pendientes.':'Planilla guardada en Supabase.');if(!dirty&&branch!=='WEB'){preparePrint();window.print();}}catch(e){status(/duplicate key|23505/.test(e.message)?'Ya existe una planilla para esta fecha y sucursal. Abrila desde Historial para actualizarla.':e.message,true);}finally{b.disabled=false;}};
 function preparePrint(){
  $('printNotes').textContent=data.notes;
  document.title='Movimientos diarios - '+branch+' - '+data.date;
  let printed=$('printSheet');if(!printed){printed=document.createElement('div');printed.id='printSheet';$('sheet').after(printed);}
  printed.replaceChildren();if(branch==='WEB')return;
  const copy=$('sheet').cloneNode(true), t=CajaMath.shared(data,branch), w=t.web?data.webClose.data:null;
  copy.querySelector('#sharedPanel')?.remove();
  if(w){
   copy.querySelector('.f9-block').innerHTML='<div class="print-f9-line"><strong>F9 TOTAL AVELLANEDA LOCAL</strong><span>'+money(t.local.saleTotal)+'</span></div><div class="print-f9-line"><strong>F9 TOTAL WEB</strong><span>'+money(t.web.saleTotal)+'</span></div>';
   for(const [key] of sections){
    const body=copy.querySelector('[data-movement="'+key+'"] tbody');
    for(const row of body.rows){const cell=row.querySelector('td.print-value');if(cell)cell.textContent='LOCAL · '+cell.textContent;}
    for(const r of w[key]||[]){
     const values=[('WEB · '+r.name)+(r.staffCode?' · LEGAJO '+r.staffCode:'')];
     if(key==='deposits')values.push(r.account==='other'?r.otherAccount:r.account||'');
     if(['deposits','vouchers'].includes(key))values.push(key==='vouchers'?(r.kind==='goods'?'MERCADERÍA':'EFECTIVO'):(r.kind==='external'?'TRANSFERENCIA EXTERNA':'DESDE CAJA'));
     values.push(money(r.amount));if(['vouchers','withdrawals'].includes(key))values.push(r.signature||'');
     const tr=document.createElement('tr');tr.innerHTML=values.map(v=>'<td class="print-value">'+esc(v)+'</td>').join('');body.append(tr);
    }
    const title=copy.querySelector('[data-movement="'+key+'"] h3');title.textContent=key==='vouchers'?'Vales':title.firstChild.textContent;
    copy.querySelector('#total-'+key).textContent='Total: '+money(t.local[key]+t.web[key]);
   }
   const shipping=copy.querySelector('#shipping tbody');
   for(const row of shipping.rows)row.cells[0].textContent='LOCAL · '+row.cells[0].textContent;
   for(const r of w.shipping||[]){const tr=document.createElement('tr');tr.innerHTML='<td>WEB · '+esc(r.name)+'</td><td class="print-value">'+money(r.cash)+'</td><td class="print-value">'+money(r.digital)+'</td><td>'+money((CajaMath.cents(r.cash)+CajaMath.cents(r.digital))/100)+'</td>';shipping.append(tr);}
   const closing=[['Total MPago + MPQR',Number(data.mp||0)+Number(w.mp||0)],['Tarjetas LOCAL',Number(data.cards||0)],['Tarjetas WEB',Number(w.cards||0)],['Total Go Cuotas',Number(data.go||0)+Number(w.go||0)],['Efectivo contado TOTAL',Number(data.counted||0)]];
   copy.querySelector('#closingInputs').innerHTML=closing.map(([label,value])=>'<div class="closing-field"><span>'+label+'</span><strong>'+money(value)+'</strong></div>').join('');
   copy.querySelector('#printNotes').textContent=(data.notes?'LOCAL: '+data.notes:'')+(w.notes?'\nWEB: '+w.notes:'');
   copy.querySelector('#responsiblePrint').textContent=data.responsible+' · LEGAJO '+data.responsibleCode+' / WEB: '+w.responsible+' · LEGAJO '+(w.responsibleCode||'');
  }
  // Copy live values explicitly: edited form controls are properties rather than HTML attributes.
  const originals=$('sheet').querySelectorAll('input,select,textarea');
  for(const control of originals){if(!control.id)continue;const target=copy.querySelector('#'+control.id);if(target&&'value' in target)target.value=control.value;}
  copy.querySelector('#responsible').classList.add('print-hide-responsible');
  copy.querySelector('#printNotes').style.whiteSpace='pre-wrap';
  copy.removeAttribute('id');for(const el of copy.querySelectorAll('[id]'))el.removeAttribute('id');
  printed.append(...copy.childNodes);
 }
 $('printButton').onclick=async()=>{if(branch==='WEB')return;try{if(branch==='AV2'&&data.sharedDrawer)await checkWeb();validate();preparePrint();window.print();}catch(e){status(e.message,true);}};
 window.addEventListener('beforeprint',preparePrint);
 if(branch==='WEB'){for(const id of ['printButton','dockPrint'])$(id).hidden=true;$('saveButton').textContent='Guardar cierre';$('dockSave').textContent='Guardar cierre';}
 else if(branch==='AV2'){$('saveButton').textContent='Guardar e imprimir';$('dockSave').textContent='Guardar e imprimir';}
 async function history(reset=true){if(reset){offset=0;$('historyList').replaceChildren();}const rows=await request({action:'list',offset});for(const r of rows){const b=document.createElement('button');b.textContent=r.business_date+' · '+r.data.responsible+' · '+money(r.totals.final);b.onclick=()=>{if(dirty&&!confirm('Hay cambios pendientes de guardar en Supabase. ¿Reemplazar el borrador por esta planilla?'))return;data=CajaRules.normalize({...blank(),sharedDrawer:false,...r.data});webState='loading';record={id:r.id,date:r.business_date,version:r.version};dirty=false;persist();render();checkWeb();status('Planilla recuperada de Supabase.');window.scrollTo({top:0,behavior:'smooth'});};$('historyList').append(b);}offset+=rows.length;$('more').hidden=rows.length<30;if(reset&&!rows.length)$('historyList').textContent='Todavía no hay planillas guardadas.';}
 $('historyButton').onclick=async()=>{try{$('history').hidden=false;await history();}catch(e){status(e.message,true);}};$('more').onclick=async()=>{try{await history(false);}catch(e){status(e.message,true);}};
 const newButton=document.createElement('button');newButton.type='button';newButton.textContent='Nueva planilla';newButton.onclick=()=>{if(dirty&&!confirm('Hay cambios pendientes de guardar en Supabase. ¿Descartar este borrador y empezar una planilla vacía?'))return;data=blank();webState='loading';latestWeb=null;record=null;dirty=false;persist();render();checkWeb();status('Nueva planilla. Completá la fecha y los movimientos del día.');};document.querySelector('.actions').prepend(newButton);
 // Delegación para cubrir también los montos de las filas agregadas después.
 $('sheet').addEventListener('keydown',e=>{if(e.target.matches('input[data-money]')&&['ArrowUp','ArrowDown'].includes(e.key))e.preventDefault();});
 $('sheet').addEventListener('wheel',e=>{if(e.target.matches('input[data-money]')&&document.activeElement===e.target)e.target.blur();},{passive:true});
 window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
 render();loadStaff();loadAccounts();checkWeb();status(dirty?'Borrador recuperado · pendiente de guardar en Supabase.':'Primero ingresá el F9 informado por Dragon. Después completá los movimientos y el arqueo.');
})();
