create table if not exists public.inc_employees (
  code text primary key check (code ~ '^[0-9]{1,20}$'),
  first_name text not null,
  last_name text not null,
  full_name text generated always as (btrim(first_name || ' ' || last_name)) stored,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.inc_tickets (
  id uuid primary key default gen_random_uuid(),
  incident_number bigint generated by default as identity unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  status text not null default 'Abierto' check (status in ('Abierto','En proceso','Resuelto','Cerrado','Rechazado')),
  priority text not null check (priority in ('Baja','Media','Alta','Crítica')),
  branch text not null check (char_length(branch) between 1 and 80),
  reporter_code text not null check (char_length(reporter_code) between 1 and 80),
  reporter_name text not null default '' check (char_length(reporter_name) <= 100),
  area text not null check (char_length(area) between 1 and 80),
  title text not null check (char_length(title) between 1 and 100),
  description text not null check (char_length(description) between 1 and 2000),
  attachments jsonb not null default '[]'::jsonb check (jsonb_typeof(attachments) = 'array'),
  assignee_code text not null default '' check (char_length(assignee_code) <= 20),
  assignee text not null default '' check (char_length(assignee) <= 100)
);

create table if not exists public.inc_history (
  id bigint generated always as identity primary key,
  ticket_id uuid not null references public.inc_tickets(id) on delete cascade,
  created_at timestamptz not null default now(),
  status text not null check (status in ('Abierto','En proceso','Resuelto','Cerrado','Rechazado')),
  assignee_code text not null default '' check (char_length(assignee_code) <= 20),
  assignee text not null default '' check (char_length(assignee) <= 100),
  note text not null default '' check (char_length(note) <= 1000)
);

create index if not exists inc_tickets_updated_idx on public.inc_tickets (updated_at desc);
create index if not exists inc_tickets_status_idx on public.inc_tickets (status, updated_at desc);
create index if not exists inc_tickets_branch_idx on public.inc_tickets (branch, updated_at desc);
create index if not exists inc_history_ticket_idx on public.inc_history (ticket_id, created_at);

create table if not exists public.inc_rate_limits (
  rate_key text not null,
  window_start timestamptz not null,
  request_count integer not null default 1,
  primary key (rate_key, window_start)
);

alter table public.inc_employees enable row level security;
alter table public.inc_tickets enable row level security;
alter table public.inc_history enable row level security;
alter table public.inc_rate_limits enable row level security;

revoke all on public.inc_employees, public.inc_tickets, public.inc_history, public.inc_rate_limits from anon, authenticated;
grant all on public.inc_employees, public.inc_tickets, public.inc_history, public.inc_rate_limits to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.inc_take_rate(p_key text, p_limit integer, p_seconds integer)
returns boolean
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_window timestamptz := to_timestamp(floor(extract(epoch from clock_timestamp()) / p_seconds) * p_seconds);
  v_count integer;
begin
  if p_key is null or p_limit < 1 or p_seconds < 1 then return false; end if;
  insert into public.inc_rate_limits(rate_key, window_start, request_count)
  values (left(p_key, 200), v_window, 1)
  on conflict (rate_key, window_start)
  do update set request_count = public.inc_rate_limits.request_count + 1
  returning request_count into v_count;
  delete from public.inc_rate_limits where window_start < now() - interval '2 days';
  return v_count <= p_limit;
end;
$$;

create or replace function public.inc_create_ticket(p jsonb)
returns public.inc_tickets
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_ticket public.inc_tickets;
begin
  insert into public.inc_tickets (
    branch, reporter_code, reporter_name, area, priority, title, description, attachments
  ) values (
    btrim(p->>'branch'), btrim(p->>'reporterCode'), left(btrim(coalesce(p->>'reporterName','')),100),
    btrim(p->>'area'), btrim(p->>'priority'), left(btrim(p->>'title'),100),
    left(btrim(p->>'description'),2000), coalesce(p->'attachments','[]'::jsonb)
  ) returning * into v_ticket;
  return v_ticket;
end;
$$;

create or replace function public.inc_update_ticket(p jsonb)
returns public.inc_tickets
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_ticket public.inc_tickets;
  v_number bigint;
begin
  v_number := nullif(regexp_replace(coalesce(p->>'id',''), '\D', '', 'g'), '')::bigint;
  update public.inc_tickets
     set status = btrim(p->>'status'),
         assignee_code = left(btrim(coalesce(p->>'assigneeCode','')),20),
         assignee = left(btrim(coalesce(p->>'assignee','')),100),
         updated_at = now()
   where incident_number = v_number
   returning * into v_ticket;
  if v_ticket.id is null then raise exception 'Incidente no encontrado'; end if;
  if v_ticket.assignee_code = '' or v_ticket.assignee = '' then raise exception 'Responsable inválido'; end if;
  insert into public.inc_history(ticket_id,status,assignee_code,assignee,note)
  values (v_ticket.id,v_ticket.status,v_ticket.assignee_code,v_ticket.assignee,left(btrim(coalesce(p->>'note','')),1000));
  return v_ticket;
end;
$$;

revoke all on function public.inc_take_rate(text,integer,integer) from public, anon, authenticated;
revoke all on function public.inc_create_ticket(jsonb) from public, anon, authenticated;
revoke all on function public.inc_update_ticket(jsonb) from public, anon, authenticated;
grant execute on function public.inc_take_rate(text,integer,integer) to service_role;
grant execute on function public.inc_create_ticket(jsonb) to service_role;
grant execute on function public.inc_update_ticket(jsonb) to service_role;

insert into storage.buckets (id, name, public, file_size_limit)
values ('inc-attachments','inc-attachments',false,10485760)
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit;

insert into public.inc_employees(code,first_name,last_name) values
('138','ALEJANDRA','SOSA'),('22','ANA','QUISPE'),('115','Ana María','Santaella'),('36','ANGEL','CONTRERAS'),
('145','ANTONELA','LOPEZ'),('222','ANTONELLA','CORBALAN'),('14','ANTONELLA','SANCHEZ'),('46','ANTONELLA GISELLE LOPEZ','LOPEZ'),
('195','AYLEN','CHAILE'),('161','BRENDA','GARCIA'),('33','BRENDA','RAMIREZ'),('15','Brisa','Cabral Cabado'),
('79','DAIANA','LOPEZ'),('99','DAMIAN','GARCIA'),('110','DIEGO','MORA'),('44','ELISA','GEREZ'),
('35','ERIKA','ALCANTARA'),('215','FLORENCIA','FERNANDEZ JUGO'),('26','FLORENCIA ABIGAIL','SANCHEZ'),('45','FLORENCIA AGUSTINA','RAPARI'),
('178','FRANCO','INFANTINO'),('88','Gabriela','Suazo'),('212','GABRIELA','HURIÑANCO'),('91','GISEL','ROTELA'),
('130','HECTOR ANIBAL','MOYANO'),('37','JESUS','SARZANO'),('72','JOEL','PEREZ'),('104','KARINA','SILVA'),
('11','LAURA','HOSORIO'),('116','LEANDRO','GONZALEZ'),('54','LUCIANO','RIVERA'),('50','MAGALI','IBAÑEZ'),
('226','MAIA','ROMANO'),('219','MARCELO','PEREZ'),('87','MARISOL','DIAZ'),('16','MATIAS','GONZALEZ'),
('34','MAYRA','OLIVA'),('41','MELINA','REY'),('198','MELINA','SEVERINI'),('85','MICAELA','BILA'),
('47','Miguel Emiliano','Servioli'),('5','Milagros','Domínguez'),('158','MILAGROS CANDELA','DIAZ'),('20','Nahuel','Peralta'),
('153','NAIR','RUIZ'),('76','NICOLE','AGUILAR'),('21','NICOLE','DIAZ'),('189','ORIANA','GUZZARDI FARIAS'),
('207','OSVALDO','MIRANDA'),('29','PATRICIA','ROMERO'),('181','RAMON','MATOS'),('206','RODRIGO','CELARIO'),
('73','ROMINA','CUELLO'),('81','SELENA','VARGA'),('75','SERGIO','SILVA'),('42','SOLANA','CAPUTTE'),
('56','SOLEDAD','AYALA'),('186','SOLEDAD','SIERRA'),('180','SUSANA','DELBOY'),('196','TANIA','AGUIRRE'),
('59','TIARA','REYES'),('129','TRINIDAD','MORON'),('7','Yanina','Córdoba'),('12','YASMIN','DELAO'),
('83','YESICA','GATICA'),('58','YESICA','LEZCANO')
on conflict (code) do update set first_name=excluded.first_name,last_name=excluded.last_name,active=true,updated_at=now();
