const fs=require('node:fs'),path=require('node:path'),root=path.resolve(__dirname,'..');
fs.mkdirSync(path.join(root,'vendor'),{recursive:true});
for(const [source,dest] of [['dexie/dist/dexie.min.js','dexie.min.js'],['papaparse/papaparse.min.js','papaparse.min.js'],['dexie/LICENSE','dexie.LICENSE'],['papaparse/LICENSE','papaparse.LICENSE']])fs.copyFileSync(path.join(root,'node_modules',source),path.join(root,'vendor',dest));
const output=path.join(root,'deployment');fs.mkdirSync(output,{recursive:true});
fs.writeFileSync(path.join(output,'Code.gs'),['shared/domain.js','server/engine.js','server/google-adapter.gs','server/stations.gs','server/entry.gs','server/smoke.gs'].map(f=>fs.readFileSync(path.join(root,f),'utf8')).join('\n\n'));
fs.copyFileSync(path.join(root,'server/appsscript.json'),path.join(output,'appsscript.json'));
const resources=JSON.parse(fs.readFileSync(path.join(output,'resources.json'),'utf8'));
fs.writeFileSync(path.join(output,'Install.gs'),`/* Resources already created for this installation. No secrets. */\nfunction installPreparedPickingV2(){\n var props=PropertiesService.getScriptProperties();\n if(props.getProperty('PICKING_CONFIG'))throw new Error('Ya configurado: no se sobrescribe.');\n var cfg=${JSON.stringify(resources,null,2)};\n var control=SpreadsheetApp.openById(cfg.controlId),book=SpreadsheetApp.openById(cfg.cuadernoId);\n if(!control.getSheetByName('CONTROL')||!control.getSheetByName('PENDIENTES')||!book.getSheetByName(cfg.cuadernoSheet))throw new Error('Pestañas incompletas.');\n DriveApp.getFolderById(cfg.backupFolderId).getName();\n Object.keys(cfg.routes).forEach(function(k){DriveApp.getFolderById(cfg.routes[k]).getName();});\n control.setSpreadsheetTimeZone('America/Argentina/Buenos_Aires');book.setSpreadsheetTimeZone('America/Argentina/Buenos_Aires');\n props.setProperty('PICKING_CONFIG',JSON.stringify(cfg));\n\n installPickingRecovery();\n console.log('Instalación piloto preparada. Cuadernillo: '+book.getUrl());\n}\n`);
console.log('Vendor y paquete de Apps Script actualizados.');
