(() => {
'use strict';
if(!window.RioContext?.canUse({slug:'revision-stock',restricted:true}))return;
const DATA_URL=window.STOCK_VENTAS_API_URL;
const SITES=['Avellaneda 3249 + Web','Avellaneda 2900','Corrientes','Sarmiento','Quilmes','PUEYRREDON','Castelli','Lamarca'];
const WEIGHTS={'Avellaneda 3249 + Web':3.25,'Avellaneda 2900':1.75,Corrientes:1,Sarmiento:1,Quilmes:1,PUEYRREDON:1,Castelli:.2,Lamarca:.2};
const FIXED_LINE={Castelli:2,Lamarca:2};
const state={data:null,rows:[],results:[],excluded:new Set(),open:new Set(),limit:20};
const $=id=>document.getElementById(id),fmt=new Intl.NumberFormat('es-AR',{maximumFractionDigits:2});

function normalize(raw){
  return raw.records.map(r=>{const stock={},sales={};for(const site of SITES){if(site==='Avellaneda 3249 + Web'){stock[site]=positive(number(r.branches['Avellaneda 3249']?.[0])+number(r.branches.Web?.[0]));sales[site]=number(r.branches['Avellaneda 3249']?.[1])+number(r.branches.Web?.[1])}else{stock[site]=positive(r.branches[site]?.[0]);sales[site]=number(r.branches[site]?.[1])}}return{code:r.code,name:r.article,supplier:r.supplier,unit:r.unit,classification:r.classification,line:r.line,group:r.group,color:r.color,size:r.size,stock,sales,totalStock:Object.values(stock).reduce((a,b)=>a+b,0),totalSales:Object.values(sales).reduce((a,b)=>a+b,0)}})
}
function positive(v){return Math.max(0,Number(v)||0)}
function number(v){return Number(v)||0}
function roundTargets(raw,total){const entries=Object.entries(raw).map(([site,value])=>({site,n:Math.floor(value),fraction:value-Math.floor(value)}));let used=entries.reduce((a,x)=>a+x.n,0);entries.sort((a,b)=>b.fraction-a.fraction);for(const x of entries){if(used>=total)break;x.n++;used++}return Object.fromEntries(entries.map(x=>[x.site,x.n]))}
function weighted(total,sites){const w=sites.reduce((a,s)=>a+(WEIGHTS[s]||0),0);return roundTargets(Object.fromEntries(sites.map(s=>[s,w?total*WEIGHTS[s]/w:0])),total)}
function isLine(v){return /(^|\s)LINEA(\s|$)/i.test(`${v.classification} ${v.line}`)}
function isPromotionUnit(v){return String(v.unit||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase().startsWith('PRO ARTICULO EN PROMOCION')}
function targets(v){
  const total=Math.floor(v.totalStock);let target;
  if(isLine(v)&&!isPromotionUnit(v)&&total>=4){const fixedSites=SITES.filter(s=>FIXED_LINE[s]!=null),fixedTotal=fixedSites.reduce((a,s)=>a+FIXED_LINE[s],0);if(total>=fixedTotal){target=Object.fromEntries(SITES.map(s=>[s,FIXED_LINE[s]||0]));Object.assign(target,weighted(total-fixedTotal,SITES.filter(s=>FIXED_LINE[s]==null)))}else target=weighted(total,SITES.filter(s=>FIXED_LINE[s]==null))}else target=weighted(total,SITES);
  const main='Avellaneda 3249 + Web';if($('priorityInput').checked&&total>=5&&(target[main]||0)<5){let pending=5-(target[main]||0);target[main]=5;for(const site of SITES.filter(s=>s!==main).sort((a,b)=>WEIGHTS[a]-WEIGHTS[b])){const take=Math.min(target[site]||0,pending);target[site]-=take;pending-=take;if(!pending)break}}
  return target;
}
function compute(v){const target=targets(v),donors=[],receivers=[];for(const site of SITES){const diff=(v.stock[site]||0)-(target[site]||0);if(diff>0)donors.push({site,qty:diff});if(diff<0)receivers.push({site,qty:-diff})}receivers.sort((a,b)=>WEIGHTS[b.site]-WEIGHTS[a.site]);donors.sort((a,b)=>WEIGHTS[a.site]-WEIGHTS[b.site]);const moves=[];for(const to of receivers)for(const from of donors){if(to.qty<=0)break;if(from.qty<=0)continue;const qty=Math.min(to.qty,from.qty);moves.push({from:from.site,to:to.site,qty});from.qty-=qty;to.qty-=qty}return{variant:v,current:v.stock,target,moves}}
function key(item,m){return[item.variant.code,item.variant.color,item.variant.size,m.from,m.to,m.qty].join('|')}
function included(item){return item.moves.filter(m=>!state.excluded.has(key(item,m)))}
function projected(item){const p={...item.current};for(const m of included(item)){p[m.from]-=m.qty;p[m.to]+=m.qty}return p}
function filtered(){const q=$('searchInput').value.trim().toLocaleLowerCase('es'),code=$('codeInput').value.trim().toLocaleLowerCase('es'),min=Number($('minStockInput').value)||0;const exact={supplier:'supplierSelect',unit:'unitSelect',classification:'classificationSelect',line:'lineSelect',group:'groupSelect',color:'colorSelect',size:'sizeSelect'};return state.rows.filter(r=>Object.entries(exact).every(([field,id])=>!$(id).value||r[field]===$(id).value)&&r.totalStock>=min&&(!$('onlyStockInput').checked||r.totalStock>0)&&(!$('onlySalesInput').checked||r.totalSales!==0)&&(!code||r.code.toLocaleLowerCase('es').includes(code))&&(!q||[r.code,r.name,r.color,r.size].join(' ').toLocaleLowerCase('es').includes(q)))}
function render(){const base=filtered(),computed=base.map(compute),branch=$('branchSelect').value;let withMoves=computed.filter(x=>x.moves.length&&(!branch||x.moves.some(m=>m.from===branch||m.to===branch)));const sort=$('sortSelect').value;withMoves.sort((a,b)=>sort==='code'?a.variant.code.localeCompare(b.variant.code,'es',{numeric:true}):sort==='stock'?b.variant.totalStock-a.variant.totalStock:sort==='sales'?b.variant.totalSales-a.variant.totalSales:included(b).reduce((s,m)=>s+m.qty,0)-included(a).reduce((s,m)=>s+m.qty,0));state.results=withMoves;const units=withMoves.reduce((a,x)=>a+included(x).reduce((s,m)=>s+m.qty,0),0);$('variantsKpi').textContent=fmt.format(base.length);$('moveVariantsKpi').textContent=fmt.format(withMoves.filter(x=>included(x).length).length);$('unitsKpi').textContent=fmt.format(units);$('excludedKpi').textContent=fmt.format(state.excluded.size);$('resultLabel').textContent=`${fmt.format(Math.min(state.limit,withMoves.length))} de ${fmt.format(withMoves.length)} variantes con movimientos`; $('exportBtn').disabled=!units; $('restoreBtn').disabled=!state.excluded.size; $('moreBtn').hidden=withMoves.length<=state.limit; const view=withMoves.slice(0,state.limit);$('movesList').innerHTML=view.length?view.map(card).join(''):'<div class="empty">No hay movimientos sugeridos con estos filtros.</div>'}
function variantKey(item){return[item.variant.code,item.variant.color,item.variant.size].join('|')}
function stockGrid(item){const next=projected(item);return `<div class="stock-table-wrap"><table class="stock-table"><thead><tr><th scope="col">Sucursal</th><th scope="col">Actual</th><th scope="col">Proyectado</th><th scope="col">Cambio</th></tr></thead><tbody>${SITES.map(site=>{const delta=(next[site]||0)-(item.current[site]||0);return `<tr><th scope="row">${esc(site.toLocaleUpperCase('es-AR'))}</th><td>${fmt.format(item.current[site]||0)}</td><td>${fmt.format(next[site]||0)}</td><td class="${delta>0?'gain':delta<0?'loss':''}">${delta>0?'+':''}${fmt.format(delta)}</td></tr>`}).join('')}</tbody></table></div>`}
function card(item){const v=item.variant,id=variantKey(item),moves=item.moves.map(m=>{const excluded=state.excluded.has(key(item,m));return `<label class="move-chip ${excluded?'excluded':''}"><input type="checkbox" data-key="${esc(key(item,m))}" ${excluded?'':'checked'}><span>${esc(m.from.toLocaleUpperCase('es-AR'))} → ${esc(m.to.toLocaleUpperCase('es-AR'))}</span><b>${fmt.format(m.qty)} u.</b></label>`}).join('');return `<details class="move-card" data-variant="${esc(id)}" ${state.open.has(id)?'open':''}><summary><div><h3>${esc(v.code)} <span>· ${esc(v.name)}</span></h3><p>${esc(v.supplier||'Sin proveedor')} · ${esc(v.color||'Sin color')} · Talle ${esc(v.size||'—')} · ${item.moves.length} movimientos</p></div><strong>${fmt.format(included(item).reduce((a,m)=>a+m.qty,0))} u.</strong></summary><div class="stock-detail">${stockGrid(item)}<div class="moves-label">Movimientos incluidos en la propuesta</div><div class="moves">${moves}</div></div></details>`}
function fill(id,values){const el=$(id),first=el.options[0].outerHTML;el.innerHTML=first+[...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es',{numeric:true})).map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}
async function load(){
  const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),60000);
  $('reloadBtn').disabled=true;$('exportBtn').disabled=true;$('movesList').setAttribute('aria-busy','true');
  try{
    $('dataStatus').textContent='Leyendo el reporte diario…';
    if(!DATA_URL)throw Error('Falta configurar la fuente del reporte.');
    const url=new URL(DATA_URL);url.searchParams.set('v',Date.now());
    const response=await fetch(url,{cache:'no-store',signal:controller.signal});
    if(!response.ok)throw Error('La fuente no pudo entregar el reporte.');
    const data=await response.json();
    if(!Array.isArray(data.records)||!/^\d{4}-\d{2}-\d{2}$/.test(data.reportDate||''))throw Error('El reporte no tiene el formato esperado.');
    state.rows=normalize(data);state.data=data;state.excluded.clear();state.open.clear();state.limit=20;
    fill('branchSelect',SITES);fill('supplierSelect',state.rows.map(x=>x.supplier));fill('unitSelect',state.rows.map(x=>x.unit));fill('classificationSelect',state.rows.map(x=>x.classification));fill('lineSelect',state.rows.map(x=>x.line));fill('groupSelect',state.rows.map(x=>x.group));fill('colorSelect',state.rows.map(x=>x.color));fill('sizeSelect',state.rows.map(x=>x.size));
    $('reportDate').textContent=new Intl.DateTimeFormat('es-AR',{dateStyle:'medium'}).format(new Date(data.reportDate+'T12:00:00'));
    $('dataStatus').textContent=`${fmt.format(state.rows.length)} variantes · ${SITES.length} sucursales operativas`;
    render();
  }catch(e){
    state.data=null;state.rows=[];state.results=[];state.excluded.clear();
    ['variantsKpi','moveVariantsKpi','unitsKpi','reportDate'].forEach(id=>$(id).textContent='—');$('excludedKpi').textContent='0';
    $('restoreBtn').disabled=true;$('moreBtn').hidden=true;$('resultLabel').textContent='Reporte no disponible';
    $('dataStatus').textContent=e.name==='AbortError'?'La consulta tardó demasiado. Volvé a actualizar.':e.message;
    $('movesList').innerHTML='<div class="empty">No se pudo cargar el reporte de stock.<br>Usá Actualizar reporte para volver a intentar.</div>';
  }finally{clearTimeout(timeout);$('reloadBtn').disabled=false;$('movesList').setAttribute('aria-busy','false')}
}
function exportMoves(){const rows=[['Código','Descripción','Proveedor','Clasificación','Grupo','Color','Talle','Desde','Hacia','Cantidad']];for(const item of state.results)for(const m of included(item))rows.push([item.variant.code,item.variant.name,item.variant.supplier,item.variant.classification,item.variant.group,item.variant.color,item.variant.size,m.from,m.to,m.qty]);if(rows.length===1)return toast('No hay movimientos para exportar');const csv=rows.map(r=>r.map(csvCell).join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF',csv],{type:'text/csv;charset=utf-8'}));a.download=`equiparacion-stock-${state.data.reportDate}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast(`${fmt.format(rows.length-1)} movimientos exportados`)}
function csvCell(v){let s=String(v??'');if(typeof v==='string'&&/^[=+@-]/.test(s))s="'"+s;return /[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
let searchTimer;['searchInput','codeInput','minStockInput'].forEach(id=>$(id).addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.limit=20;render()},180)}));['branchSelect','supplierSelect','unitSelect','classificationSelect','lineSelect','groupSelect','colorSelect','sizeSelect','onlyStockInput','onlySalesInput','priorityInput','sortSelect'].forEach(id=>$(id).addEventListener('change',render));$('clearFiltersBtn').onclick=()=>{['searchInput','codeInput','branchSelect','supplierSelect','unitSelect','classificationSelect','lineSelect','groupSelect','colorSelect','sizeSelect'].forEach(id=>$(id).value='');$('minStockInput').value=4;$('onlyStockInput').checked=$('onlySalesInput').checked=false;$('priorityInput').checked=true;$('sortSelect').value='units';render()};$('movesList').addEventListener('change',e=>{const b=e.target.closest('[data-key]');if(!b)return;const chosen=b.dataset.key;state.excluded.has(chosen)?state.excluded.delete(chosen):state.excluded.add(chosen);render();const next=Array.from($('movesList').querySelectorAll('[data-key]')).find(input=>input.dataset.key===chosen);next?.focus({preventScroll:true})});$('restoreBtn').onclick=()=>{state.excluded.clear();render()};$('moreBtn').onclick=()=>{state.limit+=20;render()};$('movesList').addEventListener('toggle',e=>{if(!e.target.isConnected||!e.target.matches('.move-card'))return;const id=e.target.dataset.variant;e.target.open?state.open.add(id):state.open.delete(id)},true);$('reloadBtn').onclick=load;$('exportBtn').onclick=exportMoves;load();

})();
