(() => {
 'use strict';
 const M=RioValesModel,$=id=>document.getElementById(id),admin=document.body.dataset.rioApp==='vales';
 let rows=[],staff=[],loading=false;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const branch=()=>window.RioContext?.branch||'';
 const status=v=>{ $('valesMessage').textContent=v; };
 async function api(action,data={}){const credentials=admin?window.RioAccess?.administrationCredentials():null;if(admin&&(!credentials||branch()!=='ADMINISTRACION'))throw new Error('La sesión de Administración terminó. Volvé al inicio para ingresar.');const r=await fetch(RioValesConfig.url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,branch:branch(),month:$('valesMonth').value,...data,...(credentials||{})}),signal:AbortSignal.timeout(25000)});const d=await r.json();if(!r.ok)throw new Error(d.error||'No se pudo completar la operación.');return d;}
 function render(){const groups=M.groups(rows);$('valesSummary').hidden=!admin;$('valesSummary').textContent=admin?`${groups.length} empleados · Solicitado: ${M.money(groups.reduce((n,g)=>n+g.total,0))}`:'';$('valesList').innerHTML=groups.length?groups.map(g=>`<section class="vale-person ${admin&&M.monthlyAlert(g)?'month-alert':''}"><h3>${esc(g.name)}</h3>${admin?`<p>Total solicitado del mes: <b>${M.money(g.total)}</b> ${M.monthlyAlert(g)?'<span class="vale-alert">Supera $500.000 mensuales</span>':''}</p><p>Aprobado en efectivo: ${M.money(g.approved)} · Mercadería: ${M.money(g.merchandise)}</p>`:''}${g.rows.map(r=>`<div class="vale-row" data-id="${esc(r.id)}"><div class="copy"><b>${M.money(r.requested_cash)}</b> ${M.requestAlert(r)?'<span class="vale-alert">Supera $100.000</span>':''} <span class="vale-status">${{pending:'A confirmar',approved:'Aprobado',rejected:'Rechazado'}[r.status]}</span><small>${esc(r.business_date)} · ${esc(window.RioContext?.label(r.branch)||r.branch)} · Mercadería: ${r.merchandise_requested?'Solicitada':'No solicitada'}</small>${r.status!=='pending'?`<small>Efectivo aprobado: ${M.money(r.approved_cash)} · Mercadería aprobada: ${M.money(r.approved_merchandise)}</small>`:''}</div>${admin?`<div class="vale-controls"><label>Efectivo aprobado<input data-cash inputmode="decimal" value="${esc(Number(r.approved_cash??r.requested_cash).toLocaleString('es-AR',{useGrouping:false}))}"></label><label>Mercadería (opcional)<input data-merch inputmode="decimal" value="${esc(Number(r.approved_merchandise||0).toLocaleString('es-AR',{useGrouping:false}))}"></label><button class="btn" data-action="approve">Aprobar</button><button class="btn" data-action="reject">Rechazar</button><button class="btn" data-action="delete">Eliminar</button></div>`:''}</div>`).join('')}</section>`).join(''):(admin?'<p>No hay solicitudes en este mes.</p>':'<p>No hay vales para mostrar esta semana.</p>');}
 async function refresh(){if(loading)return;loading=true;status('Consultando vales…');try{rows=await api(admin?'admin_list':'list');render();status('Vales actualizados.');}catch(e){if(!admin){rows=[];render();}status(e.message);}finally{loading=false;}}
 $('valesMonth').value=M.today().slice(0,7);
 $('valesMonth').onchange=refresh;$('valesRefresh').onclick=refresh;
 $('valeForm').onsubmit=async e=>{e.preventDefault();const button=$('valeSubmit');button.disabled=true;try{const code=$('valeStaff').value;if(!staff.some(s=>s.id===code))throw new Error('Seleccioná un empleado del padrón.');await api(admin?'admin_create':'create',{staffCode:code,requestedCash:M.amount($('valeCash').value),merchandiseRequested:$('valeMerchandise').checked,...(admin?{date:$('valeDate').value,targetBranch:$('valeBranch').value}:{})});$('valeCash').value='';$('valeMerchandise').checked=false;$('valesMonth').value=(admin?$('valeDate').value:M.today()).slice(0,7);await refresh();status('Solicitud guardada. Queda a confirmar.');}catch(e){status(e.message);}finally{button.disabled=false;}};
 $('valesList').onclick=async e=>{const b=e.target.closest('[data-action]');if(!b||loading)return;const el=b.closest('[data-id]'),r=rows.find(r=>r.id===el.dataset.id);if(b.dataset.action==='delete'&&!confirm(`¿Eliminar el vale de ${r.staff_name} por ${M.money(r.requested_cash)}?`))return;b.disabled=true;try{const action=b.dataset.action;await api(action==='delete'?'admin_delete':'admin_review',{id:r.id,version:r.version,...(action==='delete'?{}:{status:action==='approve'?'approved':'rejected',approvedCash:action==='approve'?M.amount(el.querySelector('[data-cash]').value):0,approvedMerchandise:action==='approve'?M.amount(el.querySelector('[data-merch]').value):0})});await refresh();}catch(err){status(err.message);}finally{b.disabled=false;}};
 if(admin){$('valeBranch').innerHTML=RioContext.branches.map(b=>`<option value="${b}">${esc(RioContext.label(b))}</option>`).join('');$('valeDate').value=M.today();if(window.RioAccess?.isUnlocked())$('valesContent').hidden=false;$('valesExport').onclick=()=>{$('valesExportDialog').showModal();};$('exportCancel').onclick=()=>{$('valesExportDialog').close();};for(const button of document.querySelectorAll('[data-export]'))button.onclick=()=>{exportImage(button.dataset.export==='high').catch(e=>status('No se pudo exportar la imagen: '+e.message));$('valesExportDialog').close();};}
 async function exportImage(onlyHigh){const selected=M.exportRows(rows,onlyHigh);if(!selected.length){status('No hay solicitudes para exportar con ese filtro.');return;}await document.fonts.ready;const perPage=70;for(let offset=0;offset<selected.length;offset+=perPage){const page=selected.slice(offset,offset+perPage);const c=await RioValesImage.build({rows:page,monthlyRows:rows,month:$('valesMonth').value,onlyHigh,pageNumber:Math.floor(offset/perPage)+1,pageCount:Math.ceil(selected.length/perPage)});await new Promise(resolve=>c.toBlob(blob=>{if(blob){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`vales-${$('valesMonth').value}-${onlyHigh?'mayores-100000':'completo'}-${Math.floor(offset/perPage)+1}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}resolve();},'image/png'));}status('Imagen de solicitudes exportada.');}
 (async()=>{try{staff=await CajaStaff.load();$('valeStaff').innerHTML='<option value="">Elegí un empleado</option>'+staff.map(s=>`<option value="${esc(s.id)}">${esc(s.nombre)} (${esc(s.id)})</option>`).join('');$('valeSubmit').disabled=false;}catch(e){status(e.message);}})();
 if(!admin||window.RioAccess?.isUnlocked())refresh();
 setInterval(()=>{if(!document.hidden&&(!admin||window.RioAccess?.isUnlocked()))refresh();},60000);
})();
